TipddyPizarraBundle_pregunta:
    resource: "@TipddyPizarraBundle/Resources/config/routing/pregunta.yml"
    prefix:   /pregunta


TipddyPizarraBundle_respuesta:
    resource: "@TipddyPizarraBundle/Resources/config/routing/respuesta.yml"
    prefix:   /respuesta		

