parameters:
#    tipddy_pizarra.example.class: Tipddy\PizarraBundle\Example

services:
#    tipddy_pizarra.example:
#        class: %tipddy_pizarra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
